# Generated by Django 2.2.4 on 2019-11-07 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('articel_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('abstract', models.TextField()),
                ('content', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
